<?php

return [
    [
        'name'    => 'enable_trial',
        'title'   => '新用户体验',
        'type'    => 'bool',
        'group'   => '免费体验',
        'content' => [],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'trial_days',
        'title'   => '免费体验天数',
        'type'    => 'number',
        'group'   => '免费体验',
        'content' => [],
        'value'   => '3',
        'rule'    => 'required;integer(+)',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => 'min="1"',
    ],
    [
        'name'    => 'controller_login_required',
        'title'   => '控制端必须登录',
        'type'    => 'bool',
        'group'   => '权限',
        'content' => [],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'controlled_guest_allowed',
        'title'   => '被控端可以不登录',
        'type'    => 'bool',
        'group'   => '权限',
        'content' => [],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'allow_expired_session_finish',
        'title'   => '到期后已有连接允许自然结束',
        'type'    => 'bool',
        'group'   => '权限',
        'content' => [],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'min_version',
        'title'   => '最低版本',
        'type'    => 'string',
        'group'   => '客户端',
        'content' => [],
        'value'   => '1.0.0',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'latest_version',
        'title'   => '最新版本',
        'type'    => 'string',
        'group'   => '客户端',
        'content' => [],
        'value'   => '1.0.0',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'update_url',
        'title'   => '更新地址',
        'type'    => 'string',
        'group'   => '客户端',
        'content' => [],
        'value'   => '',
        'rule'    => 'url',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'official_url',
        'title'   => '官网',
        'type'    => 'string',
        'group'   => '客户端',
        'content' => [],
        'value'   => '',
        'rule'    => 'url',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'agreement_url',
        'title'   => '用户协议',
        'type'    => 'string',
        'group'   => '客户端',
        'content' => [],
        'value'   => '',
        'rule'    => 'url',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'privacy_url',
        'title'   => '隐私政策',
        'type'    => 'string',
        'group'   => '客户端',
        'content' => [],
        'value'   => '',
        'rule'    => 'url',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'id_server',
        'title'   => 'ID Server',
        'type'    => 'string',
        'group'   => 'RustDesk',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'relay_server',
        'title'   => 'Relay Server',
        'type'    => 'string',
        'group'   => 'RustDesk',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'public_key',
        'title'   => 'Public Key',
        'type'    => 'text',
        'group'   => 'RustDesk',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
];
