<?php

return [
    [
        'name'    => 'appid',
        'title'   => '微信公众号 AppID',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'secret',
        'title'   => '微信公众号 AppSecret',
        'type'    => 'password',
        'content' => [],
        'value'   => '',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'token',
        'title'   => '微信公众号服务器配置 Token',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'aes_key',
        'title'   => '微信公众号消息加解密 Key',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '明文模式可留空',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'http_verify',
        'title'   => 'SSL 证书校验',
        'type'    => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value'   => '0',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '正式环境建议开启，本地联调可关闭',
        'ok'      => '',
        'extend'  => '',
    ],
];