<?php

return [
    [
        'name' => 'appid',
        'title' => '微信公众号 AppID',
        'type' => 'string',
        'content' => [],
        'value' => 'wx750d17d128b8517b',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'secret',
        'title' => '微信公众号 AppSecret',
        'type' => 'password',
        'content' => [],
        'value' => '6d0f977397660a9ccd5dc3c0a05d40df',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'token',
        'title' => '微信公众号服务器配置 Token',
        'type' => 'string',
        'content' => [],
        'value' => 'ldkj_wechat_token_2026',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'aes_key',
        'title' => '微信公众号消息加解密 Key',
        'type' => 'string',
        'content' => [],
        'value' => 'ju9ax3OpyRLShW8DlFn0Q7qtlOWsDLUKJUTdym5SV8r',
        'rule' => '',
        'msg' => '',
        'tip' => '明文模式可留空',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'http_verify',
        'title' => 'SSL 证书校验',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '正式环境建议开启，本地联调可关闭',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'http_proxy',
        'title' => '微信 API HTTP 代理',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '留空则直连；格式：http://用户名:密码@主机:端口',
        'ok' => '',
        'extend' => '',
    ],
];
