<?php

return [
    [
        'name'    => 'region',
        'title'   => '地区',
        'type'    => 'select',
        'content' => [
            'ap-beijing'=>'华北地区(北京)',
            'ap-tianjin'=>'华北地区(天津)',
            'ap-guangzhou'=>'华南地区（广州）',
            'ap-nanjing'=>'华东地区(南京)',
        ],
        'value'   => 'app-beijing',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'smsSdkAppId',
        'title'   => '短信SdkAppId',
        'type'    => 'string',
        'content' => [],
        'value'   => '1400000000',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '在腾讯云 短信控制台 添加应用后生成的实际 SdkAppId',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'secretId',
        'title'   => 'SecretId',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'secretKey',
        'title'   => 'SecretKey',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'signName',
        'title'   => '签名',
        'type'    => 'string',
        'content' => [],
        'value'   => '',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '必须填写已审核通过的签名',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'template',
        'title'   => '短信模板',
        'type'    => 'array',
        'content' => [],
        'value'   => [
            'register'           => '1000000',
            'resetpwd'           => '1000000',
            'changepwd'          => '1000000',
            'changemobile'       => '1000000',
            'profile'            => '1000000',
            'notice'             => '1000000',
            'mobilelogin'        => '1000000',
            'bind'               => '1000000',
        ],
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => '__tips__',
        'title'   => '温馨提示',
        'type'    => 'string',
        'content' => [],
        'value'   => '短信SdkAppId 你可以通过 https://console.cloud.tencent.com/smsv2/app-manage 创建',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
];
